version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  db:
    image: mysql:8.0
    container_name: project_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medzap
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  php:
    build: .
    container_name: project_php
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  react:
    image: node:18-alpine
    container_name: project_react
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    networks:
      - app-network

volumes:
  db_data: